export default {
    INCREMENT: 'COUNTER_PLUS',
    DECREMENT: 'COUNTER_MINUS',
    STEP_CHANGE: 'STEP_CHANGE',
    REQUEST_COUNTER_FETCHING: 'REQUEST_COUNTER_FETCHING',
    REQUEST_COUNTER_SUCCESS: 'REQUEST_COUNTER_SUCCESS',
    REQUEST_COUNTER_ERROR: 'REQUEST_COUNTER_ERROR'
}