module.exports = {
    SALT_ROUND: 5,
    ACCESS_EXPIRES_TIME: 60,
    REFRESH_EXPIRES_TIME: 60*60,
    ACCESS_SECRET: 'ONL-JS-FE2023-1',
    REFRESH_SECRET: '1-3202EF-SJ-LNO',
    SOCKET_REFRESH_TASK_LIST: 'SOCKET_REFRESH_TASK_LIST'
};