GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFkOTFhNmRmYmYwNWEzYWRiZmQ0NWQiLCJlbWFpbCI6InBvdHRlckBnbWFpbC5jb20iLCJpYXQiOjE2OTY2MDc2MDksImV4cCI6MTY5NjYxMTIwOX0.ZRCWWU4i81pHA7T2E-ZZAz-Yny0quDPEdKCNumSqN1c HTTP/1.1